/** Downtown City MegaKit model catalog, grouped by name prefix.
 * Generated from client/public/assets/downtown/*.gltf — keep in sync when adding models. */

export const CATALOG: { category: string; models: string[] }[] = [
  {
    category: "Streets",
    models: [
      "Street_2Lane",
      "Street_2Lane_noSidewalk",
      "Street_4Lane",
      "Street_4Lane_noSidewalk",
      "Street_4WayIntersection",
      "Street_Asphalt_6x6",
      "Street_Asphalt_9x9",
      "Street_Asphalt_Curve_2Lane",
      "Street_Asphalt_Curve_4Lane_Short",
      "Street_Curve_2Lane",
      "Street_Curve_2Lane_Curb",
      "Street_Curve_4LaneShort",
      "Street_Curve_4Lane_Short_Curb",
      "Street_TIntersection",
    ],
  },
  {
    category: "Sidewalks",
    models: [
      "Sidewalk_Corner_Flat_3m",
      "Sidewalk_Corner_Flat_3m_Stripe",
      "Sidewalk_Corner_Round_3m",
      "Sidewalk_Corner_Round_3m_Stripe",
      "Sidewalk_NoCurb_3m",
      "Sidewalk_Planter",
      "Sidewalk_Straight_3m",
      "Sidewalk_Straight_3m_Stripe",
    ],
  },
  {
    category: "Buildings",
    models: ["Building_Large_2", "Building_Medium_2_001", "Building_Small_1"],
  },
  {
    category: "Brick walls",
    models: [
      "Brick_90Angle_L",
      "Brick_90Angle_R",
      "Brick_BottomTrim",
      "Brick_Column_RedBricks",
      "Brick_Column_Small",
      "Brick_Column_TrimBricks",
      "Brick_CornerColumn_Bottom",
      "Brick_CornerColumn_Cap",
      "Brick_CornerColumn_CapShort",
      "Brick_CornerColumn_Center",
      "Brick_CornerColumn_Center_Half",
      "Brick_CornerColumn_Top",
      "Brick_Corner_Plain",
      "Brick_HalfColumn_Bottom",
      "Brick_HalfColumn_Center",
      "Brick_HalfColumn_Top",
      "Brick_HalfTrim",
      "Brick_Inset",
      "Brick_Inset_Window",
      "Brick_Inset_Window_Curved",
      "Brick_Inset_Window_Curved_Small",
      "Brick_InteriorWall_1",
      "Brick_InteriorWall_3",
      "Brick_InteriorWall_4",
      "Brick_Ornament_Horizontal",
      "Brick_Plain_1",
      "Brick_Plain_3",
      "Brick_Plain_3_noWear",
      "Brick_Plain_4",
      "Brick_RedWhite_DoubleWindow",
      "Brick_TopTrim",
      "Brick_TopTrim_90Angle_L",
      "Brick_TopTrim_90Angle_R",
      "Brick_TopTrim_Corner",
      "Brick_Window_CurvedDouble",
      "Brick_Window_Square_Single",
      "Brick_Window_Trim",
      "Brick_Window_Trim_Single",
    ],
  },
  {
    category: "Metal walls",
    models: [
      "Metal_Column_Bottom",
      "Metal_Column_Center",
      "Metal_Column_Small_Bottom",
      "Metal_Column_Small_Center",
      "Metal_Column_Small_Top",
      "Metal_Column_Top",
      "Metal_FirstFloor_Wall",
      "Metal_FirstFloor_Wall_1",
      "Metal_FirstFloor_Window",
      "Metal_FullWindow",
      "Metal_Plain_1",
      "Metal_Plain_3",
      "Metal_Window",
      "Metal_Window_Half",
    ],
  },
  {
    category: "Trim walls",
    models: [
      "Trim_90Angle_TopCover",
      "Trim_Column_Bottom",
      "Trim_Column_Center",
      "Trim_Column_Top",
      "Trim_Corner",
      "Trim_FirstFloor_Wall",
      "Trim_FirstFloor_Window_001",
      "Trim_FirstFloor_Window_Columns",
      "Trim_Plain_3",
      "Trim_Wall_Guard",
      "Trim_Window",
    ],
  },
  {
    category: "Cornices",
    models: [
      "Cornice_Brick_90Angle_L",
      "Cornice_Brick_90Angle_R",
      "Cornice_Brick_Center",
      "Cornice_Brick_L",
      "Cornice_Brick_R",
      "Cornice_Metal_90Angle_L",
      "Cornice_Metal_90Angle_R",
      "Cornice_Metal_Center",
      "Cornice_Metal_L",
      "Cornice_Metal_R",
      "Cornice_Trim_90Angle_L",
      "Cornice_Trim_90Angle_R",
      "Cornice_Trim_Center",
      "Cornice_Trim_L",
      "Cornice_Trim_R",
    ],
  },
  {
    category: "Roofs",
    models: [
      "Roof_2x2",
      "Roof_2x2_90Angle_Center",
      "Roof_2x2_90Angle_L",
      "Roof_2x2_90Angle_R",
      "Roof_4x4",
      "Roof_SlateCornice_Center",
      "Roof_SlateCornice_Corner",
      "Roof_SlateCornice_InnerCorner",
      "Roof_SlateCornice_Window_1",
      "Roof_Slate_Center",
      "Roof_Slate_Corner",
      "Roof_Slate_InnerCorner",
      "Roof_Slate_Window_1",
    ],
  },
  {
    category: "Props",
    models: ["Prop_ACUnit", "Prop_Bollard", "Prop_Drain", "Prop_ManholeCover", "Prop_Planter_Single"],
  },
  {
    category: "Decals",
    models: [
      "Decal_ArrowForwardLeft",
      "Decal_ArrowForwardRight",
      "Decal_ArrowStraight",
      "Decal_ArrowTurnLeft",
      "Decal_ArrowTurnRight",
      "Decal_Bikelane",
      "Decal_BrokenLine_Straight",
      "Decal_Crosswalk",
      "Decal_Crosswalk_Wide",
      "Decal_Curve_2Lane_Stripe",
      "Decal_Curve_4LaneShort",
      "Decal_Curve_4LaneShort_DoubleYellow",
      "Decal_Curve_4LaneShort_Stripe",
      "Decal_DoubleYellow_Straight",
      "Decal_Only",
      "Decal_Slow",
      "Decal_Stop",
    ],
  },
  {
    category: "Doors, stairs & misc",
    models: [
      "Door_1",
      "Door_2",
      "Door_3",
      "DoorFrame_Metal_Single",
      "DoorFrame_Trim",
      "DoorFrame_Wooden",
      "Entrance_Concrete_2x1",
      "Entrance_Concrete_2x2",
      "Stairs_Entrance_Concrete",
      "Stairs_Rails_Metal",
      "Stairs_Rails_Metal_Straight_1",
      "Stairs_Rails_Metal_Straight_2",
      "Floor_2x2",
      "Floor_4x4",
      "Floor_Inset",
    ],
  },
];
